[env]
TERM = "xterm-256color"

[terminal.shell]
program = "~/.config/alacritty/program.sh"

[general]
import = [ "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml" ]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

[terminal]
