[env]
TERM = "xterm-256color"

[terminal.shell]
program = "<HOME-PATH>/.config/alacritty/program.sh"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

[terminal]
